spring:
  application:
    name: GameSense

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/GameSense_Database}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 300000
      idle-timeout: 120000
      connection-timeout: 30000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: qwen3-embedding:0.6b
        options:
          keep-alive: 10m


data:
  path: ../data/

ai:
  huggingface:
    api-key: ${HF_API_KEY}
    base-url: https://router.huggingface.co/v1
    chat:
      model:  Qwen/Qwen3-32B
      temperature: 0.2
      max-tokens: 400
      enable-thinking: false

retrieval:
  embedding:
    dimension: 1024
    tok-k: 3